// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNIm-dnrintWZ0aoiH_0NZ8vyfiuN-iJY',
    appId: '1:1019331275909:web:35259373dd5669e8f30dec',
    messagingSenderId: '1019331275909',
    projectId: 'dusome-45a6c',
    authDomain: 'dusome-45a6c.firebaseapp.com',
    databaseURL: 'https://dusome-45a6c-default-rtdb.firebaseio.com',
    storageBucket: 'dusome-45a6c.appspot.com',
    measurementId: 'G-VLBJR4B55Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5WFWShaH-DiRhkYVQ1qXmfcSatojlpEs',
    appId: '1:1019331275909:android:771909de21ecef3af30dec',
    messagingSenderId: '1019331275909',
    projectId: 'dusome-45a6c',
    databaseURL: 'https://dusome-45a6c-default-rtdb.firebaseio.com',
    storageBucket: 'dusome-45a6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCZNsGNCJ0OawkfDVovUEQ0Yh3As44HP0',
    appId: '1:1019331275909:ios:e11cccb99bcb5677f30dec',
    messagingSenderId: '1019331275909',
    projectId: 'dusome-45a6c',
    databaseURL: 'https://dusome-45a6c-default-rtdb.firebaseio.com',
    storageBucket: 'dusome-45a6c.appspot.com',
    iosClientId: '1019331275909-ij0d2ocla8b2cust0u1tsd2ko7s2alab.apps.googleusercontent.com',
    iosBundleId: 'com.example.dusomeapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCZNsGNCJ0OawkfDVovUEQ0Yh3As44HP0',
    appId: '1:1019331275909:ios:e11cccb99bcb5677f30dec',
    messagingSenderId: '1019331275909',
    projectId: 'dusome-45a6c',
    databaseURL: 'https://dusome-45a6c-default-rtdb.firebaseio.com',
    storageBucket: 'dusome-45a6c.appspot.com',
    iosClientId: '1019331275909-ij0d2ocla8b2cust0u1tsd2ko7s2alab.apps.googleusercontent.com',
    iosBundleId: 'com.example.dusomeapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNIm-dnrintWZ0aoiH_0NZ8vyfiuN-iJY',
    appId: '1:1019331275909:web:ec0c80e095ccc890f30dec',
    messagingSenderId: '1019331275909',
    projectId: 'dusome-45a6c',
    authDomain: 'dusome-45a6c.firebaseapp.com',
    databaseURL: 'https://dusome-45a6c-default-rtdb.firebaseio.com',
    storageBucket: 'dusome-45a6c.appspot.com',
    measurementId: 'G-7EMPT1KMLJ',
  );
}
